stages:
    - test
    - build
    - deploy

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 1

# Test stage
fmt:
    stage: test
    image: golang:1.25
    script:
        - go fmt ./...
        - go vet ./...

# Build Docker image
build:
    stage: build
    image: docker:24
    services:
        - docker:24-dind
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    before_script:
        - until docker info; do sleep 1; done
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - main
        - tags
